spring:
  application:
    name: ms-books-payments
  datasource:
    url: jdbc:h2:mem:ms-books-payments-db;Mode=MySQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

server:
  port: 8081

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true
#    hostname: ms-books-payments